Fix endpoints accessibility
saaranganand/vibe-276 pull request #56
Opened 2024-04-02 05:34 UTC by allengao04

Fix endpoints accessibility from explore to profile, bulletin to profile. 
Not sure if it will conflict with sam's code, 
Do Not Approve it yet, Wait til Sam approve it

2024-04-03 17:18 UTC, csooyeonii approved these changes

2024-04-05 19:39 UTC, zslsam1127 submitted a review, later dismissed

2024-04-05 19:44 UTC, saaranganand requested changes

2024-04-05 19:44 UTC, saaranganand commented on vibe/src/main/java/com/vibeapp/vibe/controllers/AnnouncementController.java
> +        List<Announcement> announcements = announceRepo.findAllByOrderByAidAsc();
```suggestion
        List<Announcement> announcements = announceRepo.findAllByOrderByAidDesc();

```
AidAsc() isnt an available method

2024-04-05 20:06 UTC, saaranganand approved these changes

2024-04-05 20:10 UTC, csooyeonii approved these changes

2024-04-05 20:13 UTC, zslsam1127 approved these changes

2024-04-05 20:13 UTC, merged